export const sidebarStyles = {
  sidebar: { width:"220px", height:"100vh", backgroundColor:"#0f172a", padding:"0", position:"fixed", left:0, top:0, display:"flex", flexDirection:"column", borderRight:"1px solid #1e293b", zIndex:100 },
  sidebarBrand: { padding:"20px 20px 16px", borderBottom:"1px solid #1e293b", display:"flex", alignItems:"center", gap:"10px" },
  brandIcon: { width:"32px", height:"32px", borderRadius:"8px", background:"#1a56db", display:"flex", alignItems:"center", justifyContent:"center", color:"#fff", fontWeight:"700", fontSize:"14px", flexShrink:0 },
  brandName: { color:"#f1f5f9", fontWeight:"600", fontSize:"15px", margin:0, lineHeight:1.2 },
  brandSub: { color:"#64748b", fontSize:"11px", margin:"2px 0 0" },
  navSection: { padding:"16px 12px 8px", flex:1 },
  navLabel: { fontSize:"10px", fontWeight:"600", color:"#475569", textTransform:"uppercase", letterSpacing:"0.08em", padding:"0 8px", marginBottom:"8px", display:"block" },
  navBtn: { display:"flex", alignItems:"center", gap:"10px", width:"100%", padding:"9px 12px", borderRadius:"8px", border:"none", background:"transparent", color:"#94a3b8", fontSize:"13px", fontWeight:"500", cursor:"pointer", textAlign:"left", marginBottom:"2px" },
  navBtnActive: { background:"#1e293b", color:"#e2e8f0" },
  navIcon: { fontSize:"15px", width:"18px", textAlign:"center" },
  sidebarFooter: { padding:"16px 20px", borderTop:"1px solid #1e293b" },
  footerText: { color:"#475569", fontSize:"11px", margin:0, lineHeight:1.5 },
};

export const navItems = [
  { icon:"🏠", label:"Dashboard", path:"/" },
  { icon:"🧾", label:"Bills", path:"/bills" },
  { icon:"👨‍⚕️", label:"Patients", path:"/patients" },
  { icon:"🩺", label:"Doctors", path:"/doctors" },
  { icon:"📅", label:"Appointments", path:"/appointments" },
  { icon:"💊", label:"Treatments", path:"/treatments" },
  { icon:"📊", label:"Reports", path:"/reports" },
];

export const modalStyles = {
  // Dark blurred backdrop
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(2,6,23,0.72)",
    backdropFilter: "blur(6px)",
    WebkitBackdropFilter: "blur(6px)",
    zIndex: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  modal: {
    background: "#fff",
    borderRadius: "16px",
    width: "600px",
    maxWidth: "calc(100vw - 40px)",
    boxShadow: "0 24px 80px rgba(2,6,23,0.35)",
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100vh - 40px)",
    overflow: "hidden",
  },
  header: {
    padding: "20px 26px 16px",
    borderBottom: "1px solid #e2e8f0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
  },
  title: { fontSize:"17px", fontWeight:"700", color:"#0f172a" },
  closeBtn: {
    background: "none",
    border: "none",
    color: "#94a3b8",
    cursor: "pointer",
    fontSize: "20px",
    lineHeight: 1,
    padding: "4px 8px",
    borderRadius: "7px",
  },
  body: {
    padding: "22px 26px",
    overflowY: "auto",
    overflowX: "hidden",
    flex: 1,
  },
  footer: {
    padding: "16px 26px",
    borderTop: "1px solid #e2e8f0",
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    flexShrink: 0,
    background: "#fff",
  },
  input: {
    padding: "10px 13px",
    border: "1.5px solid #e2e8f0",
    borderRadius: "9px",
    fontSize: "13px",
    color: "#0f172a",
    fontFamily: "inherit",
    outline: "none",
    background: "#fff",
    width: "100%",
  },
  select: {
    padding: "10px 30px 10px 13px",
    border: "1.5px solid #e2e8f0",
    borderRadius: "9px",
    fontSize: "13px",
    color: "#0f172a",
    fontFamily: "inherit",
    outline: "none",
    background: "#fff",
    width: "100%",
    appearance: "none",
    backgroundImage: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%2394a3b8' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 11px center",
  },
  label: { fontSize:"10px", fontWeight:"700", color:"#64748b", textTransform:"uppercase", letterSpacing:"0.06em" },
  formGroup: { display:"flex", flexDirection:"column", gap:"5px", marginBottom:"14px" },
  grid2: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:"14px", marginBottom:"14px" },
  errBox: { background:"#fef2f2", border:"1px solid #fecaca", borderRadius:"9px", padding:"10px 14px", color:"#dc2626", fontSize:"12px", marginBottom:"14px" },
  cancelBtn: { background:"#f1f5f9", color:"#475569", border:"none", padding:"10px 20px", borderRadius:"9px", fontSize:"13px", fontWeight:"600", cursor:"pointer", fontFamily:"inherit" },
  saveBtn: { background:"#2563eb", color:"#fff", border:"none", padding:"10px 20px", borderRadius:"9px", fontSize:"13px", fontWeight:"600", cursor:"pointer", fontFamily:"inherit" },
  editActionBtn: { background:"#eff6ff", color:"#2563eb", border:"1px solid #bfdbfe", padding:"10px 20px", borderRadius:"9px", fontSize:"13px", fontWeight:"600", cursor:"pointer", fontFamily:"inherit" },
  detailLabel: { fontSize:"10px", fontWeight:"700", color:"#94a3b8", textTransform:"uppercase", letterSpacing:"0.05em", marginBottom:"3px" },
  detailValue: { fontSize:"13px", color:"#0f172a", fontWeight:"500" },
  sectionLabel: { fontSize:"10px", fontWeight:"700", color:"#94a3b8", textTransform:"uppercase", letterSpacing:"0.07em", marginBottom:"10px" },
  divider: { border:"none", borderTop:"1px solid #f1f5f9", margin:"18px 0" },
  avatarRow: { display:"flex", alignItems:"center", gap:"13px", padding:"14px 16px", background:"#f8fafc", borderRadius:"11px", border:"1px solid #f1f5f9", marginBottom:"18px" },
  readGrid: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:"14px" },
};